pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  stock:
    projectId: citric-campaign-349210
    publisher:
      internalOrdersTopicId: core.internal.orders
    consumer:
      brokerMockOrdersTopicId: broker_mock.orders
      brokerMockOrdersSubId: broker_mock.orders.sub
  broker:
    - id: common_broker
      projectId: mock_broker_project_id
      consumer: broker.pending_orders
rest:
  stock:
    stockExchangeCore: http://mock.com

general:
  rest:
    port: 5005