pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  stock:
    projectId: angelic-bond-366421
    publisher:
      internalOrdersTopicId: core.internal.orders
    consumer:
      brokerMockOrdersTopicId: broker_mock.orders
      brokerMockOrdersSubId: broker_mock.orders.sub
  broker:
    - id: common_broker
      projectId: broker-366421
      consumer:
        brokerPendingOrdersTopicId: broker.pending_orders
        brokerPendingOrdersSubId: broker.pending_orders.sub
rest:
  stock:
    stockExchangeCore: http://mock.com

general:
  rest:
    port: 5006