pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: my-second-project-364017
    publisher:
      brokerPendingOrdersTopicId: broker.internal.orders
    consumer:
      brokerInternalClientOrdersTopicId: broker.internal.client_orders
      brokerInternalClientOrdersSubId: broker.internal.client_orders.sub

rest:
  stock:
    orderExecutor: http://mock.com

general:
  rest:
    port: 5011