pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: my-second-project-364017
    consumer:
      brokerOrdersTopicId: broker.orders.status
      brokerOrdersSubId: broker.orders.status.sub
    publisher:
      brokerInternalOrdersStatusTopicId: broker.internal.orders_status

rest:
  broker:
    brokerCore: http://mock.com
    priceStreamer: http://mock.com

general:
  rest:
    port: 5015