version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=qwe
      - COUCHDB_PASSWORD=qwe
    volumes:
      - ./dbdata:/opt/couchdb/data