from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ProcessingTimestamps:
    client_order_send: Optional[int] = field(default=None)
    broker_facade_order_received: Optional[int] = field(default=None) 
    broker_facade_order_sending: Optional[int] = field(default=None)
    broker_facade_order_send: Optional[int] = field(default=None)
    broker_core_order_received: Optional[int] = field(default=None)
    broker_core_order_processing: Optional[int] = field(default=None)
    broker_core_order_processed: Optional[int] = field(default=None)
    broker_core_order_sending: Optional[int] = field(default=None)
    broker_core_order_send: Optional[int] = field(default=None)
    broker_order_executor_order_received: Optional[int] = field(default=None)
    broker_order_executor_order_sending: Optional[int] = field(default=None)
    broker_order_executor_order_send: Optional[int] = field(default=None)
    stock_order_collector_order_received: Optional[int] = field(default=None)
    stock_order_collector_order_sending: Optional[int] = field(default=None)
    stock_order_collector_order_send: Optional[int] = field(default=None)
    stock_core_order_received: Optional[int] = field(default=None)
    stock_core_order_processing: Optional[int] = field(default=None)
    stock_core_order_processed: Optional[int] = field(default=None)
    stock_core_status_sending: Optional[int] = field(default=None)
    stock_core_status_send: Optional[int] = field(default=None)
    broker_order_status_collector_status_received: Optional[int] = field(default=None)
    broker_order_status_collector_status_sending: Optional[int] = field(default=None)
    broker_order_status_collector_status_send: Optional[int] = field(default=None)
    broker_core_status_received: Optional[int] = field(default=None)
    broker_core_status_processing: Optional[int] = field(default=None)
    broker_core_status_processed: Optional[int] = field(default=None)
    broker_core_status_sending: Optional[int] = field(default=None)
    broker_core_status_send: Optional[int] = field(default=None)
    broker_data_streamer_status_received: Optional[int] = field(default=None)
    broker_data_streamer_status_sending: Optional[int] = field(default=None)
    broker_data_streamer_status_send: Optional[int] = field(default=None)
    client_status_received: Optional[int] = field(default=None)
