pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: my-second-project-364017
    consumer:
      brokerInternalPricesTopicId: broker.internal.prices
      brokerInternalPricesSubId: broker.internal.prices.streamer.sub

rest:
  broker:
    brokerCore: http://mock.com
    priceStreamer: http://mock.com

general:
  rest:
    port: 5014