firestore:
  stock:
    projectId: citric-campaign-349210

pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  stock:
    projectId: citric-campaign-349210
    publisher:
      pricesTopicId: core.prices
    consumer:
      internalOrdersTopicId: core.internal.orders
      internalOrdersSubId: core.internal.orders.sub
  broker:
    - id: common_broker
      projectId: my-second-project-364017
      publisher:
        ordersStatusTopicId: broker.orders.status

rest:
  broker:
    - id: common_broker
      ordersStatus: http://mock.com

general:
  rest:
    port: 5005