firestore:
  stock:
    projectId: https://angelic-bond-366421-18971.europe-west1.firebasedatabase.app/

pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  stock:
    projectId: angelic-bond-366421
    publisher:
      pricesTopicId: core.prices
    consumer:
      internalOrdersTopicId: core.internal.orders
      internalOrdersSubId: core.internal.orders.sub
  broker:
    - id: common_broker
      projectId: broker-366421
      publisher:
        ordersStatusTopicId: broker.orders.status

rest:
  broker:
    - id: common_broker
      ordersStatus: http://mock.com

general:
  rest:
    port: 5005