firestore:
  broker:
    projectId: broker-366421

pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: broker-366421
    publisher:
      brokerInternalClientOrdersTopicId: broker.internal.client_orders
    consumer:
      clientMockOrdersTopicId: client_mock.orders
      clientMockOrdersSubId: client_mock.orders.sub

rest:
  stock:
    brokerCore: http://mock.com

general:
  rest:
    port: 5012