pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  stock:
    projectId: angelic-bond-366421
    consumer:
      corePricesTopicId: core.prices
      corePricesSubId: core.prices.sub
  broker:
    projectId: broker-366421
    publisher:
      brokerInternalPricesTopicId: broker.internal.prices

rest:
  broker:
    brokerCore: http://mock.com
    priceStreamer: http://mock.com

general:
  rest:
    port: 5013