pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: broker-366421
    consumer:
      brokerInternalPricesTopicId: broker.internal.prices
      brokerInternalPricesSubId: broker.internal.prices.streamer.sub
      brokerInternalCoreOrdersStatusTopicId: broker.internal.core.orders_status
      brokerInternalCoreOrdersStatusSubId: broker.internal.core.orders_status.sub

rest:
  broker:
    brokerCore: http://mock.com
    priceStreamer: http://mock.com

general:
  rest:
    port: 5014