identity: common_broker
pubsub:
  listenerType: pull
  publisherType: push
  publisherLocal: True
  broker:
    projectId: broker-366421
    publisher:
      brokerPendingOrdersTopicId: broker.pending_orders
    consumer:
      brokerInternalOrdersTopicId: broker.internal.orders
      brokerInternalOrdersSubId: broker.internal.orders.sub

rest:
  stock:
    orderCollector: http://mock.com

general:
  rest:
    port: 5010